version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn --batch-mode --update-snapshots clean package -DskipTests
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn --batch-mode --update-snapshots verify
workflows:
  version: 2
  maven_build:
    jobs:
    - build
    - test:
        requires:
        - build